config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new'
  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get  "/explore", to: 'static_pages#explore'
  get  '/about', to: 'static_pages#about'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  #Sessions to login and logout users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end


  resources :account_activations, only: [:edit]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 10)
    end
  end

  def explore
  end

  def about

  end

  def contact

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
  <div class="jumbotron">
    <center><h1>About Us</h1></center>
    <p>Tweeted is a service for friends, family, and coworkers to communicate and stay connected through the exchange of quick, frequent messages. People post Tweets, which may contain photos, videos, links, and text. These messages are posted to your profile, sent to your followers, and are searchable on Tweeted search.</p>

    <div class="row center">
      <div class="col-lg-4">
        <%= fa_stacked_icon "twitter", base: "square-o", class: "font-icon center" %>

      </div>
      <div class="col-lg-4">

         <%= fa_stacked_icon "camera-retro", class: "font-icon center" %>
      </div>
      <div class="col-lg-4">

         <%= fa_stacked_icon "users", base: "square-o", class: "font-icon center" %>
      </div>
    </div> 
  </div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>

app/views/static_pages/explore.html.erb
<% provide(:title, "Explore") %>
  <!-- EXPLORE HEAD -->
      <div class="row">
        <div class="col-md-12 center">
          <h1 >Explore</h1>
          <p class="lead">Tweeted is the next level social media platform to connect with your friends and family. Come and join the Tweeted family!</p>
          <%= link_to "Find Out More", about_path, class: "btn btn-warning" %>  
        </div>
      </div>

 <hr>
      <div class="row">
        <div class="col-md-6">
          <%= image_tag "explore.jpeg", class: "img-responsive img-circle" %>
        </div>
        <div class="col-md-6">
          <h3>Explore & Connect</h3>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Labore reiciendis, voluptate at alias laborum odit aliquid tempore perspiciatis repudiandae hic?</p>
          <div>
   
            <div>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi distinctio iusto, perspiciatis mollitia natus harum?
            </div>
            <br>

            <div >
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi distinctio iusto, perspiciatis mollitia natus harum?
            </div>
            <br>

            <div >
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi distinctio iusto, perspiciatis mollitia natus harum?
            </div>
          </div>
        </div>
      </div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>  
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Tweeted,<br> <small>a social media company</small></h1>



    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-info" %> <br> <br>

  <%= link_to image_tag("icon.png", alt: "Rails logo"),
              'https://www.linkedin.com/in/petertran-web-developer/' %>
              <p><small>Please log in to access all functionalities</small></p>
     </div>
           
<% end %>